### ISSUE TITLE
About the technique of Mixed-Precision Quantization Search

### ISSUE THREAD

**Issue by jerrykidcs** [xuke225/EQ-Net#2]
Hi! I'm very interested in your wonderful work! And I'm curious about how to acquire the training data of your MLP in CQAP.  Maybe I have ignored it in your code.  Hope for your reply sincerely! Thanks!

**Comment by HanLeI187** [comment]
Thanks for your interest in our work, the data for training CQAP is to be produced by yourself according to different models.
